# Generated by Django 5.2 on 2025-05-06 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("emotion_feedback", "0002_userfeedback_user_alter_userfeedback_session"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="emotionfeedback",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="emotionfeedback",
            name="image",
        ),
        migrations.RemoveField(
            model_name="feedbacksession",
            name="user",
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="emotion",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="emotion_image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.product",
            ),
        ),
        migrations.AlterField(
            model_name="emotionfeedback",
            name="emotion",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="rating",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="emotion_feedback.feedbacksession",
            ),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="EmotionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="emotion_images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
